
CC = gcc

LIB_DIR = lib

LIB_SOURCES = $(wildcard $(LIB_DIR)/*.c)

THREAD_EXECUTABLE = thread
PROCESS_EXECUTABLE = process

.PHONY: all clean

all: $(THREAD_EXECUTABLE) $(PROCESS_EXECUTABLE)

$(THREAD_EXECUTABLE): $(THREAD_EXECUTABLE).c $(LIB_SOURCES)
	$(CC) -o $@ $(LIB_SOURCES) $(THREAD_EXECUTABLE).c  -lpthread

$(PROCESS_EXECUTABLE): $(PROCESS_EXECUTABLE).c $(LIB_SOURCES)
	$(CC) -o $@ $(LIB_SOURCES) $(PROCESS_EXECUTABLE).c

clean:
	rm -f $(PROCESS_EXECUTABLE) $(THREAD_EXECUTABLE) $(THREAD_EXECUTABLE)_output $(PROCESS_EXECUTABLE)_output